language: c
install: test -e .travis-opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10.0+beta1 OCAML_BETA=enable
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11
  - OCAML_VERSION=4.12
os:
  - freebsd
  - linux
  - osx
arch:
  - amd64
  - arm64
